image: Ubuntu1804
stack: node 14
branches:
  only:
    - main
cache: node_modules
install:
  - yarn install
build: off
build_script:
  - yarn run build
artifacts:
  - path: dist.zip
deploy:
  - provider: GitHub
    auth_token:
      secure: Lf9/IBEE4u5AT69Sb1gZLI8VdHYq75umPAZ7gHw7GwpTTbbHrCTIEXdVt1og20B7
    artifact: dist.zip
    draft: true
    on:
      branch: main