image: Ubuntu1804
stack: node 14
branches:
  only:
    - main
cache: node_modules
install:
  - npm install
build: off
deploy:
  - provider: GitHub
    auth_token: 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
    artifact: dist
    draft: true
    on:
      branch: main