version: 1.0.{build}
image: Visual Studio 2019
environment:
  nodejs_version: "14"
  GH_REPO: "khomiakovnn/events"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
build_script:
  - yarn install
  - yarn build
artifacts:
  - path: dist
deploy:
  - provider: GitHub
    auth_token: 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
    artifact: dist
    draft: true
    on:
      branch: main
